FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5001 57300/udp

ENV NODE_ENV=development
ENV REMOTE_HOST=0.0.0.0
ENV REMOTE_PORT=5001

CMD ["node", "remote-proxy.js"]